-- Drops stale test databases left by earlier runs: worker databases (test_*) and
-- migrated templates (app_template_*). Never touches postgres or any other database.
-- Run through psql, for example: make deps-clean (the statements are
-- generated by a query and executed one by one with psql's \gexec).
\set ON_ERROR_STOP on

SELECT format('DROP DATABASE IF EXISTS %I WITH (FORCE)', datname)
FROM pg_database
WHERE datname ~ '^(app_template_|test_)'
ORDER BY datname
\gexec