apiVersion: 1

policies:
  - receiver: slack-default

    routes:
      - receiver: telegram
        matchers:
          - severity = "critical"

      - receiver: telegram
        matchers:
          - severity = "warning"