apiVersion: 1

policies:
  - receiver: telegram

    routes:
      - receiver: telegram
        matchers:
          - severity = "critical"

      - receiver: telegram
        matchers:
          - severity = "warning"